#version: "3.8"

services:
  app:
    build:
      context: ./app  # ⬅️ Ensure Docker is looking inside `/srv/laravel/app`
      dockerfile: ../docker/Dockerfile
    container_name: laravel_app
    volumes:
      - ./app:/var/www/html  # ⬅️ Mount Laravel app directory
    environment:
      APP_ENV: production
      APP_DEBUG: false
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pipeline
      MYSQL_USER: pipeline
      MYSQL_PASSWORD: pipeline@1210
    depends_on:
      - mysql
    networks:
      - laravel_network

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    volumes:
      - ./app:/var/www/html  # ⬅️ Mount Laravel app directory
      - ./docker/nginx/pipeline.conf:/etc/nginx/conf.d/default.conf  # ⬅️ NGINX config
      - ./certs:/etc/nginx/certs  # ⬅️ SSL certificates
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pipeline
      MYSQL_USER: pipeline
      MYSQL_PASSWORD: pipeline@1210
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:

